"""
In-app bug report dialog.

Collects system info automatically, lets the user describe the issue,
generates a formatted Markdown report, saves it to ~/Downloads, and
opens a pre-filled GitHub issue in the browser with the report as the body.
"""


import platform
import re
import sys
import webbrowser
from datetime import datetime
from pathlib import Path
from urllib.parse import quote

from PyQt6.QtWidgets import (
    QCheckBox, QComboBox, QDialog, QFrame, QHBoxLayout,
    QLabel, QLineEdit, QPushButton, QScrollArea,
    QTextEdit, QVBoxLayout, QWidget,
)

_GITHUB_ISSUES_URL = "https://github.com/ONEPUNCHMAN411/Jarvis/issues/new"
_MAX_URL_BODY = 4000  # GitHub URL limit for pre-filled body


def _clean(text: str) -> str:
    return re.sub(r"\r\n?", "\n", text or "").strip()


def _collect_sysinfo(runtime=None) -> dict:
    info = {
        "jarvis_version": "1",
        "os": f"Windows {platform.version()}",
        "python": sys.version.split()[0],
        "arch": platform.machine(),
        "cpu": "Unknown",
        "ram": "Unknown",
        "provider": "Unknown",
    }
    try:
        import psutil
        mem = psutil.virtual_memory()
        info["ram"] = f"{mem.total / 1024**3:.1f} GB"
        info["cpu"] = platform.processor() or "Unknown"
    except Exception:
        pass
    if runtime:
        try:
            info["provider"] = runtime._effective_primary_provider()
        except Exception:
            pass
    return info


def _render_markdown(fields: dict, sysinfo: dict) -> str:
    sev = fields["severity"]
    ts  = datetime.now().strftime("%Y-%m-%d %H:%M")

    lines = [
        f"# Bug Report: {fields['title'] or 'Untitled'}",
        "",
        f"**Severity:** {sev}  ",
        f"**Date:** {ts}  ",
        f"**Version:** JARVIS {sysinfo['jarvis_version']}  ",
        "",
        "## Description",
        "",
        fields["description"] or "_No description provided._",
        "",
        "## Steps to Reproduce",
        "",
    ]

    steps = [s.strip() for s in fields["steps"].splitlines() if s.strip()]
    if steps:
        for i, s in enumerate(steps, 1):
            lines.append(f"{i}. {s}")
    else:
        lines.append("_No steps provided._")

    lines += [
        "",
        "## Expected Behaviour",
        "",
        fields["expected"] or "_Not specified._",
        "",
        "## Actual Behaviour",
        "",
        fields["actual"] or "_Not specified._",
        "",
    ]

    if fields["logs"]:
        lines += [
            "## Logs / Error Output",
            "",
            "```",
            fields["logs"][:2000],
            "```",
            "",
        ]

    if fields["include_sysinfo"]:
        lines += [
            "## System Information",
            "",
            "| Field | Value |",
            "|---|---|",
            f"| OS | {sysinfo['os']} |",
            f"| CPU | {sysinfo['cpu']} |",
            f"| RAM | {sysinfo['ram']} |",
            f"| Python | {sysinfo['python']} |",
            f"| Active Provider | {sysinfo['provider']} |",
            "",
        ]

    lines += ["---", "*Generated by JARVIS in-app bug reporter*"]
    return "\n".join(lines)


class BugReportDialog(QDialog):
    def __init__(self, parent=None, runtime=None):
        super().__init__(parent)
        self._runtime = runtime
        self._sysinfo = _collect_sysinfo(runtime)

        self.setWindowTitle("Report a Bug")
        self.resize(640, 700)
        if parent:
            self.setStyleSheet(parent.styleSheet())

        self._build_ui()

    def _build_ui(self) -> None:
        root = QVBoxLayout(self)
        root.setSpacing(10)
        root.setContentsMargins(20, 20, 20, 16)

        # Header
        h = QLabel("Bug Report")
        h.setStyleSheet("font-size:18px;font-weight:700;color:#00C8E8;letter-spacing:2px;")
        root.addWidget(h)

        sub = QLabel("Fill in what you can — system info is collected automatically.")
        sub.setStyleSheet("color:rgba(148,163,184,0.65);font-size:11px;")
        root.addWidget(sub)

        root.addWidget(self._divider())

        # Scrollable form
        scroll = QScrollArea()
        scroll.setWidgetResizable(True)
        scroll.setFrameShape(QFrame.Shape.NoFrame)
        scroll.setStyleSheet("background:transparent;")
        inner = QWidget()
        form = QVBoxLayout(inner)
        form.setSpacing(10)
        form.setContentsMargins(0, 0, 8, 0)

        F = ("background:rgba(15,23,42,0.85);border:1px solid rgba(0,200,232,0.2);"
             "border-radius:8px;padding:7px 11px;color:#F8FAFC;font-size:13px;")
        L = "color:rgba(148,163,184,0.85);font-size:11px;font-weight:600;"

        # Title
        form.addWidget(self._lbl("Bug title *", L))
        self._title = QLineEdit()
        self._title.setPlaceholderText("One-line summary of the issue")
        self._title.setStyleSheet(F)
        form.addWidget(self._title)

        # Severity
        form.addWidget(self._lbl("Severity", L))
        self._severity = QComboBox()
        self._severity.addItems([
            "Low — cosmetic or minor inconvenience",
            "Medium — feature broken, workaround exists",
            "High — major feature broken, no workaround",
            "Critical — crash or data loss",
        ])
        self._severity.setStyleSheet(
            F + "QComboBox::drop-down{border:none;}"
            "QComboBox QAbstractItemView{background:rgba(15,23,42,0.97);color:#F8FAFC;}"
        )
        form.addWidget(self._severity)

        # Description
        form.addWidget(self._lbl("Description *", L))
        self._description = QTextEdit()
        self._description.setPlaceholderText("What went wrong? What were you trying to do?")
        self._description.setFixedHeight(90)
        self._description.setStyleSheet(F)
        form.addWidget(self._description)

        # Steps
        form.addWidget(self._lbl("Steps to reproduce  (one per line)", L))
        self._steps = QTextEdit()
        self._steps.setPlaceholderText("1. Open JARVIS\n2. Ask it to...\n3. See error")
        self._steps.setFixedHeight(80)
        self._steps.setStyleSheet(F)
        form.addWidget(self._steps)

        # Expected / Actual side by side
        ea = QHBoxLayout()
        ea.setSpacing(10)
        lft = QVBoxLayout()
        lft.addWidget(self._lbl("Expected behaviour", L))
        self._expected = QTextEdit()
        self._expected.setPlaceholderText("What should have happened?")
        self._expected.setFixedHeight(70)
        self._expected.setStyleSheet(F)
        lft.addWidget(self._expected)

        rgt = QVBoxLayout()
        rgt.addWidget(self._lbl("Actual behaviour", L))
        self._actual = QTextEdit()
        self._actual.setPlaceholderText("What actually happened?")
        self._actual.setFixedHeight(70)
        self._actual.setStyleSheet(F)
        rgt.addWidget(self._actual)

        ea.addLayout(lft)
        ea.addLayout(rgt)
        form.addLayout(ea)

        # Logs
        form.addWidget(self._lbl("Error message / logs  (optional)", L))
        self._logs = QTextEdit()
        self._logs.setPlaceholderText("Paste any error or log output here")
        self._logs.setFixedHeight(70)
        self._logs.setStyleSheet(F)
        form.addWidget(self._logs)

        # Include sysinfo toggle
        self._include_sys = QCheckBox("Include system info  (OS, CPU, RAM, active provider)")
        self._include_sys.setChecked(True)
        self._include_sys.setStyleSheet("color:rgba(148,163,184,0.8);font-size:12px;")
        form.addWidget(self._include_sys)

        form.addStretch()
        scroll.setWidget(inner)
        root.addWidget(scroll, 1)

        root.addWidget(self._divider())

        # Status + buttons
        btn_row = QHBoxLayout()
        self._status_lbl = QLabel("")
        self._status_lbl.setStyleSheet("color:rgba(148,163,184,0.65);font-size:11px;")
        btn_row.addWidget(self._status_lbl, 1)

        for text, slot, primary in [
            ("Cancel",            self.reject,         False),
            ("Save .md",          self._save,          False),
            ("Save & Open Issue", self._save_and_open, True),
        ]:
            btn = QPushButton(text)
            btn.setStyleSheet(
                f"background:rgba(0,200,232,{'0.22' if primary else '0.08'});"
                f"border:1px solid rgba(0,200,232,{'0.5' if primary else '0.25'});"
                f"border-radius:8px;padding:7px {'18px' if primary else '14px'};"
                f"color:#00C8E8;font-weight:{'700' if primary else '500'};"
            )
            btn.clicked.connect(slot)
            btn_row.addWidget(btn)

        root.addLayout(btn_row)

    def _lbl(self, text: str, style: str) -> QLabel:
        l = QLabel(text)
        l.setStyleSheet(style)
        return l

    def _divider(self) -> QFrame:
        f = QFrame()
        f.setFrameShape(QFrame.Shape.HLine)
        f.setStyleSheet("color:rgba(0,200,232,0.12);")
        return f

    def _fields(self) -> dict:
        sev_map = {0: "Low", 1: "Medium", 2: "High", 3: "Critical"}
        return {
            "title":         _clean(self._title.text()),
            "severity":      sev_map.get(self._severity.currentIndex(), "Medium"),
            "description":   _clean(self._description.toPlainText()),
            "steps":         _clean(self._steps.toPlainText()),
            "expected":      _clean(self._expected.toPlainText()),
            "actual":        _clean(self._actual.toPlainText()),
            "logs":          _clean(self._logs.toPlainText()),
            "include_sysinfo": self._include_sys.isChecked(),
        }

    def _write_file(self) -> Path | None:
        f = self._fields()
        if not f["title"] and not f["description"]:
            self._set_status("Add a title or description first.", error=True)
            return None
        md = _render_markdown(f, self._sysinfo)
        ts = datetime.now().strftime("%Y-%m-%d_%H-%M")
        dest = Path.home() / "Downloads" / f"JARVIS-bug-{ts}.md"
        try:
            dest.write_text(md, encoding="utf-8")
            return dest
        except Exception as e:
            self._set_status(f"Could not save: {e}", error=True)
            return None

    def _set_status(self, msg: str, error: bool = False) -> None:
        color = "#FB7185" if error else "#10B981"
        self._status_lbl.setStyleSheet(f"color:{color};font-size:11px;")
        self._status_lbl.setText(msg)

    def _save(self) -> Path | None:
        dest = self._write_file()
        if dest:
            self._set_status(f"Saved → {dest.name}")
        return dest

    def _save_and_open(self) -> None:
        dest = self._write_file()
        f    = self._fields()
        body = _render_markdown(f, self._sysinfo)
        if len(body) > _MAX_URL_BODY:
            body = body[:_MAX_URL_BODY] + "\n\n_(truncated — attach the saved .md file)_"

        url = (
            f"{_GITHUB_ISSUES_URL}"
            f"?title={quote('[Bug] ' + (f['title'] or 'Issue'))}"
            f"&body={quote(body)}"
            f"&labels={quote('bug')}"
        )
        webbrowser.open(url)

        if dest:
            self._set_status(
                f"Saved {dest.name} to Downloads — attach it to the GitHub issue."
            )
        else:
            self._set_status("GitHub issue opened. Add a title/description before submitting.")
